name: controller
author: vu-ase
source: https://github.com/vu-ase/controller
version: 1.0.0
description: the authority on all steering decisions

commands:
  build: make build
  run: ./bin/controller

inputs:
  - service: imaging
    streams:
      - path

outputs:
  - decision

configuration:
  - name: speed
    type: float
    tunable: true
    value: 0.2
  - name: kp
    type: float
    tunable: true
    value: 0.01
  - name: kd
    type: float
    tunable: true
    value: 0
  - name: ki
    type: float
    tunable: true
    value: 0
  - name: desired-trajectory-point
    type: float
    tunable: false
    value: 320 # 640 / 2
