name: controller
author: vu-ase
source: https://github.com/vu-ase/controller
version: 1.0.0
description: the authority on all steering decisions

commands:
  build: make build 
  run: ./bin/controller


inputs:
  - service: imaging
    streams:
      - path

outputs:
  - decision

configuration:
  - name: speed
    type: number
    value: 1.0
    mutable: true
  - name: kp
    type: number
    value: 0.01
    mutable: true
  - name: kd
    type: number
    value: 0
    mutable: true
  - name: ki
    type: number
    value: 0
    mutable: true
  - name: desired-trajectory-point
    type: number
    value: 320 # 640 / 2
    mutable: false
